version: "3"
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    hostname: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project_database
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
      - ./backups:/tmp/backups
      - ./scripts/restore_script.sh:/docker-entrypoint-initdb.d/backup_restore.sh
      - ./backups/schema.sql:/tmp/backups/schema.sql
      - ./backups/data.sql:/tmp/backups/data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgresdb_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    networks:
      - postgresdb_network

volumes:
  postgresdb_data:
  pgadmin4_data:

networks:
  postgresdb_network:
    driver: bridge
